// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotorCyclePoland.Database;

#nullable disable

namespace MotorCyclePoland.Migrations
{
    [DbContext(typeof(MotorDbContext))]
    [Migration("20240722160034_test12345634")]
    partial class test12345634
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MotoCyclePoland.Database.Tables.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Junak"
                        },
                        new
                        {
                            Id = 3,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Suzuki"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Triumph"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ducati"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Harley-Davidson"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Kawasaki"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Indian"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Aprilia"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Barton"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Husaberg"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Yamaha"
                        },
                        new
                        {
                            Id = 14,
                            Name = "KTM"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Royal"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Zipp"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Voge"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Zontes"
                        },
                        new
                        {
                            Id = 19,
                            Name = "MV"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Benelli"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Keeway"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Lambretta"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Romet"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Bajaj"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Cagiva"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Husqvarna"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Kymco"
                        },
                        new
                        {
                            Id = 28,
                            Name = "RMT"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Piaggio"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Bimota"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Hyosung"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Buell"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Derbi"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Moto"
                        });
                });

            modelBuilder.Entity("MotoCyclePoland.Database.Tables.Motocycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("Displacement")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndProduction")
                        .HasColumnType("datetime2");

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartProduction")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Motocycles");
                });

            modelBuilder.Entity("MotoCyclePoland.Database.Tables.Motocycle", b =>
                {
                    b.HasOne("MotoCyclePoland.Database.Tables.Brand", "Brand")
                        .WithMany("Motocycles")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("MotoCyclePoland.Database.Tables.Brand", b =>
                {
                    b.Navigation("Motocycles");
                });
#pragma warning restore 612, 618
        }
    }
}
