// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotorCyclePoland.Database;

#nullable disable

namespace MotorCyclePoland.Migrations
{
    [DbContext(typeof(MotorDbContext))]
    [Migration("20240722160819_test123456343")]
    partial class test123456343
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MotoCyclePoland.Database.Tables.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Junak"
                        },
                        new
                        {
                            Id = 3,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Suzuki"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Triumph"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ducati"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Harley-Davidson"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Kawasaki"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Indian"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Aprilia"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Barton"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Husaberg"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Yamaha"
                        },
                        new
                        {
                            Id = 14,
                            Name = "KTM"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Royal"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Zipp"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Voge"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Zontes"
                        },
                        new
                        {
                            Id = 19,
                            Name = "MV"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Benelli"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Keeway"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Lambretta"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Romet"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Bajaj"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Cagiva"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Husqvarna"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Kymco"
                        },
                        new
                        {
                            Id = 28,
                            Name = "RMT"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Piaggio"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Bimota"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Hyosung"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Buell"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Derbi"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Moto"
                        });
                });

            modelBuilder.Entity("MotoCyclePoland.Database.Tables.Motocycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("Displacement")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndProduction")
                        .HasColumnType("datetime2");

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartProduction")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Motocycles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " CBR 600 F3",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " SR 400",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 3,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " F 900GS",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 4,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " GSX-S 1000GX",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 5,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " Daytona 660",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 6,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " Scrambler Icon",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 7,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " Street Glide CVO",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 8,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " Z900 SE",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 9,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " Challenger Dark Horse",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 10,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " Shiver 750",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 11,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " NXT 250L",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 12,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " FE 501",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 13,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " Tracer 7007 GT",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 14,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " 690 SMC",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 15,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " Enfield Continental GT 650 Twin",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 16,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " Scrambler 125",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 17,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " 300AC",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 18,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " 125 G1",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 19,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " Agusta Brutale 1000RR",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 20,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " 752 S",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 21,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " RKF 125",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            BrandId = 22,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " V125 Special 125",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            BrandId = 23,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " 727S",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            BrandId = 24,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " Pulsar 125",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            BrandId = 25,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " Raptor 650",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            BrandId = 26,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " VITPILEN 701",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            BrandId = 27,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " New DOWNTOWN 125",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            BrandId = 28,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " Daystar 125",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            BrandId = 29,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " X9 500 Evolution",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            BrandId = 30,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " Tesi 3D 1100",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            BrandId = 31,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " GV 125C Aquila 2012",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            BrandId = 32,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " 1125R",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            BrandId = 33,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " Senda Baja 125 SM",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            BrandId = 34,
                            Displacement = 0,
                            HorsePower = 0,
                            Name = " Guzzi V7 Racer 750",
                            StartProduction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MotoCyclePoland.Database.Tables.Motocycle", b =>
                {
                    b.HasOne("MotoCyclePoland.Database.Tables.Brand", "Brand")
                        .WithMany("Motocycles")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("MotoCyclePoland.Database.Tables.Brand", b =>
                {
                    b.Navigation("Motocycles");
                });
#pragma warning restore 612, 618
        }
    }
}
